repo:
  url: "https://github.com/MounirCloudy/monitoring-tools-stack.git"
  target: "monitoring-tools-stack"

test:
  command: "pytest -v"

deploy:
  branch: "main"

aws:
  sns_topic_arn: "arn:aws:sns:eu-west-3:537124950013:pydeployer"
  region: "eu-west-3"
