repo:
  url: "https://github.com/MounirCloudy/calculatrice.git"
  target: "calculatrice"

test:
  command: "python3 -m pytest tests/ -v"

deploy:
  branch: "main"

aws:
  sns_topic_arn: "arn:aws:sns:eu-west-3:537124950013:pydeployer"
  region: "eu-west-3"
